### ISSUE TITLE
Add `ref` field to support non-pull-request, non-push events

### ISSUE THREAD

**Issue by arbourd** [ouzi-dev/commit-status-updater#350]
Hey, this is a great Action! Thanks for taking the time to share it with us.

I know that this is intended for events `pull_request` and `push`, but I'd like to use it with `repository_dispatch`. The action doesn't allow me even tho I'm checking out the git repository at a specific point in time.

How about something like:

```yaml
- uses: actions/checkout@v2
  with:
    ref: "22dd0bd12b1a07d1dd"

uses: ouzi-dev/commit-status-updater@v1.0.7
  with:
    ref: "22dd0bd12b1a07d1dd"
```

Another option could be pulling the last sha from a local git repository, but that's a bit more magical.
