### ISSUE TITLE
Error: description doesn't accept 4-byte Unicode (e.g: a emoji like 🐛)

### ISSUE THREAD

**Issue by LeipeLeon** [ouzi-dev/commit-status-updater#527]
When a commit has a emoji the push fails: `description doesn't accept 4-byte Unicode`

My guess would be that  `octokit` does not handle emoji in the description e.g: [`await octokit.rest.repos.createCommitStatus({})`](https://github.com/ouzi-dev/commit-status-updater/blob/219d3f932547cad092e384c7a36bf4d963739c35/src/githubHelper.ts#L68)

Configuration:
```yml
      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: CI Rails
          status: "${{ job.status }}"
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          description: "${{ env.COMMIT_SHORT_SHA }} - ${{ env.COMMIT_MESSAGE }}"
```

Error transcript:
```
Run ouzi-dev/commit-status-updater@v2
  with:
    name: CI Rails
    status: success
    url: [REDACTED]
    description: d517328c - 🐛 nil:NilClass -> nil
    token: ***
    ignoreForks: true
    addHoldComment: false
    pendingComment: /hold
    successComment: /hold cancel
    failComment: /hold
  env:
    COMMIT_SHORT_SHA: d517328c
    COMMIT_MESSAGE: 🐛 nil:NilClass -> nil
    RUBY_VERSION: 3.3.0
Error: error while setting context status: Validation Failed: {"resource":"Status","code":"custom","field":"description","message":"description doesn't accept 4-byte Unicode"}
```
